name: Build and Release Aegis Tactical

on:
  push:
    branches: [ "main", "master" ] # سيعمل البناء عند كل تحديث للكود
  workflow_dispatch: # يتيح لك تشغيل البناء يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ضروري لمنح GitHub صلاحية رفع الملف إلى Releases

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Rename APK for Identification
      run: mv app/build/outputs/apk/release/*.apk Aegis_Tactical_v1.0.8Master.apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Aegis-Build-Output
        path: Aegis_Tactical_v1.0.8Master.apk

    - name: Release APK
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
      with:
        files: Aegis_Tactical_v1.0.8Master.apk
        tag_name: v1.0.8-Release
        name: Aegis Tactical v1.0.8-Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
