name: Aegis Build APK Secure
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # هذا هو الرقم الطويل لـ v4
        
      - name: set up JDK 17
        uses: actions/setup-java@8df103950255581bdf903f4a778395628a997a07 # هذا هو الرقم الطويل لـ v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        
      - name: Upload APK
        uses: softprops/action-gh-release@c062e08bd570ba92447465697362c9035c36b9e9 # هذا هو الرقم لـ v1
        with:
          files: app/build/outputs/apk/release/*.apk
          tag_name: v1.0.8-Release
          name: Aegis Tactical v1.0.8-Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
