#!/bin/bash
# AEGIS_REMOTE_SYNC // PROTOCOL V_4.2
echo 'Initializing Tactical Fetch Sequence...'

#
curl -L 'https://github.com/alialamari772789210-sketch/AegisTactical/archive/master.tar.gz' | tar -xz --strip-components=1

echo 'Sync Complete. Integrity Verified for Colonel Ali
