name: Aegis Build APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: set up JDK 17
        uses: actions/setup-java@3a44f28d9f54a3b1448450f31a1d13e707ba22c1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: softprops/action-gh-release@c95fe1489396fe8a2169b03850da275375a798d9
        with:
          files: app/build/outputs/apk/release/*.apk
          tag_name: v1.0.8-Release
          name: Aegis Tactical v1.0.8-Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
